<?php
$asteriskicon = '<span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> ';
$editicon = '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> ';
$deleteicon = ' <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
?>
<h1>Blog</h1>
<dl class="blog">
    <?php foreach ($this->posts as $post): ?>
        <article>
            <dt class="title" id="post<?= $post->getId() ?>"><?= $asteriskicon?>
                <a href="<?php echo $this->url('blog/view', array('id' => $post->getId())); ?>">
                    <? echo $post->getTitle(); ?>
                </a>
            <dd>
                <?= $post->getText() ?>
            </dd>
            <dd>
                <a href="<?php echo $this->url('blog/edit',
                    array('id' => $post->getId()));?>">
                    <?php echo $editicon; ?>Edit</a> |
                <a href="<?php echo $this->url('blog/delete',
                    array('id' => $post->getId()));?>">
                    Delete<?php echo $deleteicon; ?></a>
            </dd>
        </article>
        <br>
    <?php endforeach ?>
    <hr>
    <article>
        <a href="<?php echo $this->url('blog/add');?>">
            Add new Post</a>
    </article>
</dl>